# Generated by Django 6.0.7 on 2026-07-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
