# Generated by Django 6.0.7 on 2026-08-02 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
    ]
