# Generated by Django 6.0.7 on 2026-08-07 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_friend'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
