# Generated by Django 6.0.7 on 2026-08-08 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_delete_friend'),
        ('friend', '0003_room_alter_requestfriend_friend_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
